- name: Network Getting Start
  connection: network_cli
  gather_facts: false
  hosts: Switch
  tasks:
  - name: Gather interface name, mode, and vlan that interface was assigned
    cisco.ios.ios_l2_interfaces:
      state: gathered
    register: gathered
  - name: display the config
    debug:
      var: gathered