- name: Network Getting Start
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:
  - name: Gather listed vlans with provided configurations
    cisco.ios.ios_l2_interfaces:
      state: gathered
    register: gathered
  - name: display the config
    debug:
      var: gathered